Fix afg burst waveform generation and update get_model_series function
tektronix/tm_devices pull request #13
Opened 2023-09-28 21:32 UTC by michaelwagoner

2023-09-28 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tektronix/tm_devices?pullRequest=13) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tektronix/tm_devices?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tektronix/tm_devices?pullRequest=13) it.</sub>

2023-09-28 22:16 UTC, nfelt14 approved these changes

2023-09-28 22:16 UTC, nfelt14 commented
The commits must be signed for them to be able to be added.

2023-09-28 22:21 UTC, nfelt14 commented
Can you change `pull_request` to `pull_request_target` in the workflow that assigns reviewers? This will need to be changed to allow the workflow to run properly when triggered by forks.

2023-09-28 22:22 UTC, nfelt14 requested changes
See previous comments

2023-09-28 23:37 UTC, nfelt14 submitted a review, later dismissed

2023-09-28 23:38 UTC, ldantek approved these changes

2023-09-29 04:03 UTC, nfelt14 approved these changes

2023-09-29 16:20 UTC, merged