Source measurement selection API fix.
tektronix/tm_devices pull request #169
Opened 2024-03-26 11:10 UTC by v12ganesh

## Proposed changes

Please include a summary of the changes and any links to related issues. Please also include relevant motivation and context.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Functionality update (non-breaking change which updates or changes existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] CI/CD update (an update to the CI/CD workflows, scripts, and/or configurations)
- [ ] Documentation update (an update to enhance the user experience when reading through the docs)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have followed the guidelines in the [CONTRIBUTING](https://github.com/tektronix/tm_devices/blob/main/CONTRIBUTING.md) document
- [x] I have signed the CLA
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/tektronix/tm_devices/pulls) for the same update/change
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Basic linting passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added necessary documentation (if appropriate)
- [x] I have updated the Changelog with a brief description of my changes

2024-03-26 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tektronix/tm_devices?pullRequest=169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tektronix/tm_devices?pullRequest=169) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tektronix/tm_devices?pullRequest=169) it.</sub>

2024-03-26 11:55 UTC, u625355 approved these changes

2024-03-26 13:35 UTC, nfelt14 requested changes

2024-03-26 13:35 UTC, nfelt14 commented on src/tm_devices/commands/_1mlt9u_mdomsodpo/measurement.py
> +    - MEASUrement:MEAS<x>:SOUrce1 {CH<x>|MATH|R<x>|D<x>|HIStogram|RF_AMPlitude| RF_FREQuency|RF_PHASe}
It seems like there is an extra space in this set of enumerations.

2024-03-26 13:35 UTC, nfelt14 commented on src/tm_devices/commands/_1mlt9u_mdomsodpo/measurement.py
> +              menu or the 'Measure Phase' side menu. SOUrce is equivalent to SOURCE1. For SOUrce2:
Why is this referencing SOUrce2 when source 2 isn't available? The syntax appears to be hard-coded to source1.

2024-03-26 13:58 UTC, nfelt14 requested changes
The changelog should be updated

2024-03-26 17:26 UTC, nfelt14 requested changes

2024-03-26 17:26 UTC, nfelt14 commented on src/tm_devices/commands/_1mlt9u_mdomsodpo/measurement.py
> +        - ``HIStogram`` indicates the histogram is the object to be measured. HIStogram only applies
This needs references to source2 removed.

2024-03-26 17:26 UTC, nfelt14 commented on src/tm_devices/commands/_1mlt9u_mdomsodpo/measurement.py
> +            - ``HIStogram`` indicates the histogram is the object to be measured. HIStogram only
Remove reference to source2.

2024-03-27 05:34 UTC, u625355 commented on CHANGELOG.md
> +- fix: Updated the measurement source selection command for the MDO 3K, MDO4K , MSO4K and DPO4K models to work properly.
fix: Updated the measurement source selection command for the MDO 3K, MDO4K, MSO4K and DPO4K models to work properly.

2024-03-27 05:37 UTC, u625355 reviewed
fix: Updated the measurement source selection command for the MDO 3K, MDO4K, MSO4K and DPO4K models to work properly.

2024-03-27 05:37 UTC, u625355 commented on CHANGELOG.md
> +- fix: Updated the measurement source selection command for the MDO 3K, MDO4K , MSO4K and DPO4K models to work properly.
```suggestion
- fix: Updated the measurement source selection command for the MDO3K, MDO4K, MSO4K and DPO4K models to work properly.
```

2024-03-27 05:53 UTC, u625355 approved these changes

2024-03-27 13:53 UTC, nfelt14 approved these changes

2024-03-27 15:49 UTC, nfelt14 commented
@v12ganesh, @u625355 please go in and sign all of the commits.

2024-03-27 15:50 UTC, nfelt14 requested changes

2024-03-27 15:50 UTC, nfelt14 commented on CHANGELOG.md
> +- fix: Updated the measurement source selection command for the MDO3K, MDO4K, MSO4K and DPO4K models to work properly.
```suggestion
- Updated the measurement source selection command for the MDO3K, MDO4K, MSO4K and DPO4K models to work properly.
```

2024-03-28 09:26 UTC, closed without merging