Added SourceXpress APIs support and AWG defects fix.
tektronix/tm_devices pull request #255
Opened 2024-07-26 12:52 UTC by v12ganesh

## Proposed changes

Please include a summary of the changes and any links to related issues. Please also include relevant motivation and context.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Functionality update (non-breaking change which updates or changes existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] CI/CD update (an update to the CI/CD workflows, scripts, and/or configurations)
- [ ] Documentation update (an update to enhance the user experience when reading through the docs)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have followed the guidelines in the [CONTRIBUTING](https://github.com/tektronix/tm_devices/blob/main/CONTRIBUTING.md) document
- [x] I have signed the CLA
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/tektronix/tm_devices/pulls) for the same update/change
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Basic linting passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added necessary documentation (if appropriate)
- [x] I have updated the Changelog with a brief description of my changes

2024-07-26 16:07 UTC, nfelt14 requested changes

2024-07-26 16:07 UTC, nfelt14 commented on CHANGELOG.md
> +- Fixed APIs with write and query accepting arguments for AWG70KA and AWG70KB models drivers.
```suggestion
- Fixed APIs with writes and queries accepting arguments for AWG70KA and AWG70KB models drivers.
```

2024-07-26 16:07 UTC, nfelt14 commented on README.md
> +| SourceXpress         | PI              | ✅                | ✅                                  |
Add an entry to the glossary explaining what this Software Solution is.

2024-07-26 17:07 UTC, nfelt14 commented on README.md
> +| SourceXpress         | PI              | ✅                | ✅                                  |
You will also need to update the `macros.py` file to properly update the readme when the docs are generated.

2024-07-29 08:35 UTC, u625355 submitted a review, later dismissed

2024-07-29 17:41 UTC, nfelt14 requested changes
You will also need to rebase your branch with the latest from main

2024-07-29 17:41 UTC, nfelt14 commented on CHANGELOG.md
> +- Things to be included in the next release go here.
```suggestion
Things to be included in the next release go here.
```

2024-07-29 17:41 UTC, nfelt14 commented on docs/glossary.md
> +: An application to Load and play waveforms remotely for Tektronix Arbitrary Waveform Generators
```suggestion
: An application to load and play waveforms remotely for Tektronix Arbitrary Waveform Generators

```

2024-07-29 18:04 UTC, nfelt14 requested changes

2024-07-29 18:04 UTC, nfelt14 commented on docs/glossary.md
> +: An application to load and play waveforms remotely for Tektronix Arbitrary Waveform Generators
Add whitespace (newline) after this.
```suggestion
: An application to load and play waveforms remotely for Tektronix Arbitrary Waveform Generators

```

2024-07-29 22:34 UTC, nfelt14 commented
- [ ] Please sign all of your commits

2024-07-29 22:35 UTC, nfelt14 requested changes
Please sign all of your commits

2024-07-30 03:33 UTC, nfelt14 approved these changes

2024-07-30 07:37 UTC, u625355 approved these changes

2024-07-30 07:40 UTC, u625355 commented
> Please sign all of your commits

Untill you sign all of your commits, PR cannot be merged.

2024-07-30 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tektronix/tm_devices?pullRequest=255) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tektronix/tm_devices?pullRequest=255) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: v12ganesh<br/>:x: dependabot[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tektronix/tm_devices?pullRequest=255) it.</sub>

2024-07-30 16:21 UTC, v12ganesh commented
Due to merge conflicts and SSH key issue, closing this PR.

2024-07-30 16:21 UTC, closed without merging